#!/usr/bin/env bash
import math

def prime_factors(n):
factors = []
while n % 2 == 0:
factors.append(2)
n //= 2
for i in range(3, int(math.sqrt(n)) + 1, 2):
while n % i == 0:
factors.append(i)
n //= i
if n > 2:
factors.append(n)
return factors

with open("tests/rsa-16", "r") as f:
n = int(f.read())

p, q = prime_factors(n)
print(f"{n}={p}*{q}")
